exports.autoprefixer = require('autoprefixer')
exports.sugarss = require('sugarss')
exports.sorting = require('postcss-sorting')
exports.cssortie = require('cssortie')
exports.size = require('postcss-size')
exports.extend = require('postcss-extend')
exports.reset = require('postcss-css-reset')
exports.import = require('postcss-import')
exports.coloralpha = exports.colorAlpha = require('postcss-color-alpha')
exports.propertylookup = exports.propertyLookup = require('postcss-property-lookup')
